import React, { useState } from 'react';
import { Terminal, Sliders, ShieldAlert, Sparkles } from 'lucide-react';

export const GraphRagSimulator: React.FC = () => {
  const [selectedSymbol, setSelectedSymbol] = useState<'SecurityToken' | 'PaymentProcessor' | 'DatabasePool'>('SecurityToken');
  const [radius, setRadius] = useState<number>(1);

  const symbolData = {
    SecurityToken: {
      file: 'auth/token.rs',
      span: 'L1-L35',
      privacy: 'pub',
      members: [
        { name: 'secret_key', kind: 'FieldNode', privacy: 'pub(crate)' },
        { name: 'expiration', kind: 'FieldNode', privacy: 'pub' },
        { name: 'validate_token', kind: 'MethodNode', privacy: 'pub' },
      ],
    },
    PaymentProcessor: {
      file: 'billing/gateway.rs',
      span: 'L40-L120',
      privacy: 'pub',
      members: [
        { name: 'merchant_id', kind: 'FieldNode', privacy: 'private' },
        { name: 'process_transaction', kind: 'MethodNode', privacy: 'pub' },
      ],
    },
    DatabasePool: {
      file: 'db/pool.rs',
      span: 'L10-L85',
      privacy: 'pub(crate)',
      members: [
        { name: 'max_connections', kind: 'FieldNode', privacy: 'pub' },
        { name: 'acquire_connection', kind: 'MethodNode', privacy: 'pub(crate)' },
      ],
    },
  };

  const current = symbolData[selectedSymbol];

  return (
    <section className="py-12 px-6 max-w-7xl mx-auto space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
          <Terminal className="w-6 h-6 text-emerald-400" />
          Compiler-Certified Graph RAG AI Agent Slicer
        </h2>
        <p className="text-xs text-slate-400 font-mono mt-1">
          Adjust symbol and extraction radius to observe zero-hallucination prompt context slices generated by <code className="text-emerald-400">csg::slice_around</code>.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Controls */}
        <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-6">
          <h3 className="text-xs font-mono font-bold text-cyan-400 uppercase tracking-wider flex items-center gap-2">
            <Sliders className="w-4 h-4" /> Graph RAG Parameters
          </h3>

          <div className="space-y-2">
            <label className="text-xs font-mono text-slate-300 block">Target Symbol</label>
            <div className="space-y-2">
              {(['SecurityToken', 'PaymentProcessor', 'DatabasePool'] as const).map((sym) => (
                <button
                  key={sym}
                  onClick={() => setSelectedSymbol(sym)}
                  className={`w-full text-left px-3.5 py-2.5 rounded-lg text-xs font-mono transition-all ${
                    selectedSymbol === sym
                      ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 font-bold'
                      : 'bg-slate-900 text-slate-400 border border-slate-800 hover:border-slate-700'
                  }`}
                >
                  {sym}
                </button>
              ))}
            </div>
          </div>

          <div className="space-y-2">
            <div className="flex justify-between text-xs font-mono">
              <span className="text-slate-300">Graph Radius</span>
              <span className="text-emerald-400 font-bold">{radius} Hop(s)</span>
            </div>
            <input
              type="range"
              min="1"
              max="3"
              value={radius}
              onChange={(e) => setRadius(Number(e.target.value))}
              className="w-full accent-emerald-500 cursor-pointer"
            />
          </div>

          <div className="p-3 rounded-xl bg-slate-950/80 border border-emerald-500/20 text-[11px] font-mono text-slate-300 space-y-1">
            <div className="flex justify-between">
              <span className="text-slate-400">File Span:</span>
              <span className="text-cyan-400">{current.file}:{current.span}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-400">Visibility:</span>
              <span className="text-amber-400">{current.privacy}</span>
            </div>
          </div>
        </div>

        {/* Formatted Output Window */}
        <div className="lg:col-span-2 glass-panel p-6 rounded-2xl border border-slate-800 space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-xs font-mono text-emerald-400 font-semibold flex items-center gap-2">
              <Sparkles className="w-4 h-4" /> Generated LLM Context Prompt Slice
            </span>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded-md bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
              0% Hallucination Certified
            </span>
          </div>

          <pre className="bg-slate-950 p-5 rounded-xl text-xs font-mono text-emerald-400 border border-slate-800 min-h-[260px] overflow-x-auto leading-relaxed">
{`/// COMPILER-CERTIFIED SEMANTIC CONTEXT FOR SYMBOL: ${selectedSymbol}
/// File: ${current.file} | Span: ${current.span} | Privacy: ${current.privacy}
/// Graph Extraction Radius: ${radius} hop(s)
/// Connected Dependencies & Members:
${current.members
  .slice(0, radius + 1)
  .map((m) => `  - ${m.name} (${m.kind}) [Privacy: ${m.privacy}]`)
  .join('\n')}

/// COMPILER INVARIANT VERIFIED: Private boundaries enforced.`}
          </pre>

          <div className="flex items-center gap-2 p-3 rounded-lg bg-emerald-950/40 border border-emerald-500/30 text-xs text-emerald-300">
            <ShieldAlert className="w-4 h-4 text-emerald-400 shrink-0" />
            AI tools consuming this slice cannot suggest violating struct field privacy or misjudging lifetime bounds.
          </div>
        </div>
      </div>
    </section>
  );
};
